---
# tasks file for ECS-test

- name: Verify that the directory we want to use exists on the server.
  file:
    path: '{{ working_path }}'
    state: directory

- name: Create certificate private key on the server.
  openssl_privatekey:
    path: '{{ privatekey_path }}'
    passphrase: '{{ privatekey_passphrase | default(omit) }}'
    cipher: '{{ privatekey_cipher | default(omit) }}'
    type: RSA
    size: 2048

- name: Create certificate signing request on the server
  openssl_csr:
    path: '{{ csr_path }}'
    privatekey_path: '{{ privatekey_path }}'
    privatekey_passphrase: '{{ privatekey_passphrase | default(omit) }}'
    digest: sha256
    common_name: '{{ cert_common_name }}'
    organization_name: '{{ cert_organization_name | default(omit) }}'
    organizational_unit_name: '{{ cert_organizational_unit_name | default(omit) }}'
    country_name: '{{ cert_country_name | default(omit) }}'
    state_or_province_name: '{{ cert_state_or_province_name | default(omit) }}'

- name: Request a certificate from ECS
  ecs_certificate:
    path: '{{ cert_path }}'
    csr: '{{ csr_path }}'
    requester_name: '{{ requester_name }}'
    requester_email: '{{ requester_email }}'
    requester_phone: '{{ requester_phone }}'
    cert_type: '{{ cert_type }}'
    entrust_api_user: '{{ entrust_api_user }}'
    entrust_api_key: '{{ entrust_api_key }}'
    entrust_api_client_cert_path: '{{ entrust_api_client_cert_path }}'
    entrust_api_client_cert_key_path: '{{ entrust_api_client_cert_key_path }}'
    entrust_api_specification_path: '{{ entrust_api_specification_path }}'